### ISSUE TITLE
allow fluentd v0.12

### ISSUE THREAD

**Issue by shoichikaji** [frsyuki/fluent-plugin-multiprocess#2]
While the gemspec declares `gem.add_dependency "fluentd", "~> 0.10.0"`,
fluent-plugin-multiprocess works fine with fluend v0.12.2 in my environment.
So could you modify the gemspec so that it allows fluentd v0.12?

Thank you.

**Comment by frsyuki** [comment]
Good point. I updated gemspec and released new gem.

**Comment by shoichikaji** [comment]
Thank you!
